### ISSUE TITLE
Develop web service API for manually dispatching content

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/discovery-dispatcher#103]
We need a web services interface so that we can manually dispatch content if necessary.

The specification for this API is pending some discussion -- see #30 for background and Ben's [comment](https://github.com/sul-dlss/discovery-dispatcher/issues/30#issuecomment-239218280).

**Comment by drh-stanford** [comment]
Given the current purl-fetcher implementation, we could provide a simple API like the following that would query purl-fetcher's `/purls/:druid` API and dispatch the appropriate jobs for a given PURL's published public XML:

```
PUT /dispatch/:druid
```

Some questions based on this strawman would be:
- do we need to prioritize these jobs to happen quickly when there are already jobs queued?
- do we need to provide subtarget-level parameters so only jobs relavent to the given subtarget are created?
- is this sufficient for the use case(s) for manually dispatching content?

**Comment by mejackreed** [comment]
We may want to implement the `PUT/PATCH purl/:druid#update` route in PurlFetcher that could update itself from the latest xml

**Comment by drh-stanford** [comment]
@blalbrit @LynnMcRae Is a `Republish` from Argo sufficient for this functionality?

**Comment by drh-stanford** [comment]
we briefly discussed use cases and for example a forced reindex... needs more discussion
