### ISSUE TITLE
add nagios check for it for sidekiq

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/discovery-dispatcher#112]
@eefahy did you have anything in particular you wanted to tests for sidekiq. I was just going to implement a simple `Sidekiq` job count (e.g., `Sidekiq::Queue.new.size`)

**Comment by drh-stanford** [comment]
@eefahy there's a `/status/sidekiq` endpoint now that checks to see if sidekiq is alive. Please add this to nagios monitoring.
