### ISSUE TITLE
There is an `/items/new` route

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/discovery-dispatcher#30]
Do we know what this does?

Do we use this?

**Comment by mejackreed** [comment]
What should it respond to? I would suggest `POST` only.

**Comment by drh-stanford** [comment]
It looks like the API is documented here (see bullet 2): https://consul.stanford.edu/display/GRYPHONDOR/Discovery+Release+Dispatcher

but the implementation doesn't follow it.

As for the REST API -- it would be `POST` as you suggest with for the `#create` method. See http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions

**Comment by mejackreed** [comment]
So then I'm thinking.. kill `new` in favor of `create` at:

POST | /items | items#create | create a new item

**Comment by mejackreed** [comment]
Or maybe we have to support `new` in a backwards compatible way?

**Comment by drh-stanford** [comment]
I vote for kill `new` and use `create` -- no backward compatibility since `new` is supposed to behave as a UI form not an actual data creation step.

**Comment by mejackreed** [comment]
I'm thinking we can probably kill this entirely.. need to get clarification from @blalbrit or @LynnMcRae

**Comment by blalbrit** [comment]
Based on @LynnMcRae and @lmcglohon 's discussion pre-work-cycle, I don't believe `new` **or** `create` is required. They did settle on put vs. post.

**Comment by mejackreed** [comment]
Can you say more? Does there need to be an http interface?

**Comment by lmcglohon** [comment]
I believe we don't need an http interface for the dispatcher. The put versus post is for the URL built to send to the indexing service, right @blalbrit @LynnMcRae ?

**Comment by blalbrit** [comment]
The way it was spec'd, the dispatcher should serve two purposes: background task & web services app. I read that as needing an http interface so that we can manually dispatch content if necessary.

Correct me if I'm wrong @lmcglohon and @LynnMcRae  - I'm going off of this document: https://consul.stanford.edu/display/GRYPHONDOR/Discovery+Release+Dispatcher .

There is definitely a user story for this need.

**Comment by mejackreed** [comment]
Ok reading through that specification it looks like we need to do some better planning around this. It also has implications on purl-fetcher which I would like to talk with team and @LynnMcRae on.

**Comment by drh-stanford** [comment]
The implementation of the `ItemsController#new` is busted and the specs don't work correctly. I suggest that we remove this broken code and then implement the user story in another issue.

**Comment by drh-stanford** [comment]
I've created PR #101 to close this issue, and created issue #103 to discuss how we want to implement the API to manually dispatch content.
