### ISSUE TITLE
Analysis ticket for monitoring

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/discovery-dispatcher#41]

**Comment by drh-stanford** [comment]
Note that the is_it_working is checking connectivity to its purl-fetcher node. But not the service indexer endpoints. See https://github.com/sul-dlss/discovery-dispatcher/blob/master/config/initializers/is_it_working.rb#L4

**Comment by drh-stanford** [comment]
We may also want to monitor the indexing jobs somehow via `is_it_working` and that we're firing updates regularly (via cron).

Note sure checking the connectivity to `purl-fetcher` is appropriate for `is_it_working`?
