### ISSUE TITLE
Verify release="false" behavior in dispatcher

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/discovery-dispatcher#42]
Discovery Dispatcher maintains indexed based on release tags. It will

use PURL Fetcher to determine changes within the specified timeframe. For every item returned with a release tag, it will
issue an http PUT (nee POST) to the target indexer /item for every release=true
issue an http DELETE to the target indexer /item for every release=false
read the deletes file for listings within the specified timeframe
issue an http DELETE to all registered target indexers /item for each entry

**Comment by peetucket** [comment]
connected to sul-dlss/sw-indexer#69

**Comment by peetucket** [comment]
Steps to index an item:
- [x] pick an item object in argo-stage, and add release tag with appropriately configured sw target
- [x] add releaseWF to object to trigger robots
- [x] confirm workflow completes successfully
- [x] confirm purl-test page for object has release tags in public XML
- [x] check purl-fetcher-test to see if cron job picks up newly published purl
- [x] check discovery-dispatcher-test to see if polls the purl-fetcher correctly
- [x] see if configured sw target gets indexing call from discovery-dispatcher

Repeat above, but change the release tag to ="false".  The steps should all flow the same way, but the sw solr target should get a delete.

Confirm steps above with delete on solr when release="false"
- [x] pick an item object in argo-stage, and add release tag with appropriately configured sw target
- [x] add releaseWF to object to trigger robots
- [x] confirm workflow completes successfully
- [x] confirm purl-test page for object has release tags in public XML
- [x] check purl-fetcher-test to see if cron job picks up newly published purl
- [x] check discovery-dispatcher-test to see if polls the purl-fetcher correctly
- [x] see if configured sw target gets indexing call from discovery-dispatcher

**Comment by peetucket** [comment]
The chain was followed all the way through for a new item that was release=true, and then release=false.

It worked as expected with the correct messages being sent from discovery-dispatacher through the sw-indexer (i.e. the correct index/delete API calls are being made to the indexer).  However, I still see the solr document in the actual solr core, so perhaps the indexer itself is not performing the actual delete, even though it is marked as deleted in the indexer log?

Also, note that the -stage environment always appends a target of "SEARCHWORKSPREVIEW" as true no matter what is in the release tags (i.e. there is no way to unrelease from searchworkspreview).

`I, [2016-08-25T15:36:01.383326 #28753]  INFO -- : Started DELETE "/items/bb020sf5359/subtargets/SEARCHWORKS" for 171.67.23.41 at 2016-08-25 15:36:01 -0700
I, [2016-08-25T15:36:01.390580 #28753]  INFO -- : Processing by BaseIndexer::ItemsController#destroy as */*
I, [2016-08-25T15:36:01.390663 #28753]  INFO -- :   Parameters: {"default"=>{"format"=>:json}, "druid"=>"bb020sf5359", "subtarget"=>"SEARCHWORKS"}
I, [2016-08-25T15:36:01.651081 #28753]  INFO -- : Deleting bb020sf5359 on attempt 1
I, [2016-08-25T15:36:01.695032 #28753]  INFO -- : Completing bb020sf5359 successfully on attempt 1
I, [2016-08-25T15:36:01.695537 #28753]  INFO -- :   Rendered text template (0.0ms)
I, [2016-08-25T15:36:01.695735 #28753]  INFO -- : Completed 200 OK in 305ms (Views: 0.5ms)`

**Comment by peetucket** [comment]
is there a problem in this line?  

https://github.com/sul-dlss/base_indexer/blob/master/app/controllers/base_indexer/items_controller.rb#L26

should it be "indexer.delete druid, { subtarget_params => false }" instead of "indexer.index druid, { subtarget_params => false }" ?

**Comment by drh-stanford** [comment]
The spec also expects it to call `.index` for a delete -- see https://github.com/sul-dlss/base_indexer/blob/master/spec/controllers/base_indexer/items_controller_spec.rb#L23

That does seem wrong, but the `delete` method doesn't take any subtarget arguments -- see https://github.com/sul-dlss/base_indexer/blob/master/lib/base_indexer/main_indexer_engine.rb#L39

Laney probably has additional insight. I do remember Jack refactoring the HTTP API to support deletes from specific subtargets -- see https://github.com/sul-dlss/base_indexer#itemsdruidsubtargetssubtarget

**Comment by mejackreed** [comment]
Yeah from what I remember, the `index` method does deletes based on the `false` subtargets: https://github.com/sul-dlss/base_indexer/blob/298ff5f16cc54c9ec84a7d341e6afafdb7f11163/lib/base_indexer/solr/writer.rb#L20

As @drh-stanford stated... `delete` won't take any arguments.

This was the minimal controller refactor needed without changing the underlying API. It was hard to determine what code was being used by what application so I didn't want to change the internals too much. Also the models are tightly coupled to the controller API which we changed so its kind of funky.

**Comment by peetucket** [comment]
Ok, though it seems odd to me to call an "index" method and have the result be a "delete" operation (based on the release tag being false), I think I follow the logic in the code now.  I didn't actually see the solr document deleted from the "false" target though during my test, so I will do some more investigation to see why not.

**Comment by lmcglohon** [comment]
@peetucket I think we wanted to keep the delete method as a delete from all indexes separately from deleting from a specific index. I believe that the deletion from a false target wasn't implemented in discovery-dispatcher or base-indexer/discovery-indexer/sw-indexer in the original StanfordSync workcycle.

**Comment by peetucket** [comment]
yup, makes sense, just a slight quibble with the method names being confusing to read in code (e.g. call to index actually has some conditional logic that does a delete in some cases), but i don't think we need to change them

i just discovered that the document that should have been deleted from a single target via a release=false is indeed now gone...i will redo the test, perhaps it worked fine after all but i checked too soon after the delete operation and a solr commit had not yet occurred?

(druid=bb020sf5359, target=searchworks, solr core=searchworks-stage)

**Comment by peetucket** [comment]
Ok, release=false works for a single target, but I issued a manual commit to get it to delete right away for solr.  It doesn't look like we have a maxtime for autocommit in the solrconfig for at least the serachworks-stage core.  Is there a reason for that?  Should we configure solr to do autocommits?
