### ISSUE TITLE
Discrepancy between crontab and schedule.rb

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/discovery-dispatcher#65]
schedule.rb says to run the task every 15 minutes, but the crontab on the server has it running hourly.

``` sh
0 * * * * /bin/bash ...
```

**Comment by drh-stanford** [comment]
The whenever gem doesn't look like it's configured correctly in this repo...

**Comment by eefahy** [comment]
yeah - that was because we were serving schedule.rb through `shared_configs` but I'm working on removing that now.
