### ISSUE TITLE
[prod] load testing of enqueuing indexing jobs

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/discovery-dispatcher#67]
Currently is using one worker. We should start to throttle up to see what sw-indexer can handle.

**Comment by mejackreed** [comment]
We have throttled up to 4 successfully.. now testing with 8. I think though we may need to modify how many cores this machine has. Need to discuss with @eefahy and @drh-stanford

**Comment by mejackreed** [comment]
Jobs not firing with n workers seemed to be a problem with jobs that had failed multiple times. B/c they had failed multiple times they would not restart for `n**4` seconds. This caused new workers to not pickup jobs that were failing for many times as the job's "reschedule_at" threshold was not met.

**Comment by drh-stanford** [comment]
See here for where this is configured: https://github.com/sul-dlss/discovery-dispatcher/blob/master/config/deploy/stage.rb#L4

**Comment by drh-stanford** [comment]
In prod, we're currently enqueuing jobs via the purl-fetcher prod API. it'll take several hours to enqueue them all and when the sw-indexer VM is ready we'll fire off the workers.

Note that in prod right now, the crontab is cleared and delayed job workers stopped.

**Comment by drh-stanford** [comment]
We estimate the enqueuing will take 24 hours in prod and complete by morning.

**Comment by drh-stanford** [comment]
See #81
