### ISSUE TITLE
How many times should we try to send an indexing job to sw-indexer?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/discovery-dispatcher#74]
Currently we try the `Delayed::Job` default max which is 25 retries of a failed job. This is problematic as described in:

> The default Worker.max_attempts is 25. After this, the job either deleted (default), or left in the database with "failed_at" set. With the default of 25 attempts, the last retry will be 20 days later, with the last interval being almost 100 hours.
- https://github.com/collectiveidea/delayed_job#gory-details

The interval is defined as:

> On error, the job is scheduled again in 5 seconds + N *\*  4, where N is the number of attempts or using the job's defined reschedule_at method.

_Note_: in Ruby `**` is the exponent operator

So I guess what we need to know is.. How long is an indexing job request still valid? Is it a day? A week?

**Comment by drh-stanford** [comment]
I did some research and below is the configuration that sounds right to me. @blalbrit can you verify that these assumptions are ok?
1. We want to stop _retrying_ the job on failures after 3 hours (which works out to 10 attempts before giving up)
2. We want to keep _all_ the failed jobs in the queue (so we can see the errors and/or retry them)
3. We don't want any _single_ indexing job (1 druid) to take longer than 5 mins (they are typically about 1 second right now in stage)

Here's the specific syntax for this configuration that would go in `config/initializers/delayed_job.rb`:

```
# we want to keep failed jobs around since we want to be able to restart them
Delayed::Worker.destroy_failed_jobs = false

# default max_attempts is 25 which we found to be too high as it keeps retrying
# the job for many many days
Delayed::Worker.sleep_delay = 1.minute  # backoff is sleep_delay + attempts**4
Delayed::Worker.max_attempts = 10       # stops after about 3 hours

# the indexing jobs should never take more than max_run_time and
# our jobs are typically sub-second. we want to mark an error and
# move onto the next job if it does
Delayed::Worker.max_run_time = 5.minutes
```

**Comment by blalbrit** [comment]
@drh-stanford I agree with all of the assumptions above. 3 hours seems excessive maybe, but that's a good enough number.

One question - and @lmcglohon wonders this too - does one job retrying for 3 hours block other indexing jobs?

**Comment by blalbrit** [comment]
@drh-stanford - unless there's a strong reason otherwise, would a one-hour timeout be unwise, instead of three hours?

**Comment by mejackreed** [comment]
One job retrying does not block. It will only retry after `n ** 4` seconds. So it will just hang out in the queue.

Re: 1 hour time window no idea. It won't hurt anything to keep it around. Unless.. an indexing job fails ( and sits waiting for an hour). During that same time a delete job comes around and executes. Then later on the indexing job completes. This scenario would only happen if we don't add the purl checking stuff on sw-indexing.
