### ISSUE TITLE
[prod] RuntimeError: delete druid doesn't handle 500 Faraday::Response

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/discovery-dispatcher#87]
## Backtrace

```
line 59 of [PROJECT_ROOT]/lib/discovery_dispatcher/indexing_job.rb: run_request
line 18 of [PROJECT_ROOT]/lib/discovery_dispatcher/indexing_job.rb: block in perform
line 12 of [PROJECT_ROOT]/lib/discovery_dispatcher/indexing_job.rb: perform
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48973/faults/30795226)

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/discovery-dispatcher/blob/master/lib/discovery_dispatcher/indexing_job.rb#L59

**Comment by drh-stanford** [comment]
Looks like the original error is gone from Honeybadger. There's a related error here: https://app.honeybadger.io/projects/48973/faults/30880454#notice-summary

Here's the relevant line of code:

https://github.com/sul-dlss/discovery-dispatcher/blob/master/app/jobs/indexing_job.rb#L56

**Comment by drh-stanford** [comment]
@lmcglohon what should the expected behavior be if the sw-indexer returns a 500 error message when using the API for index or delete?

Right now, the job fails and is retried as well as sends an exception (`RuntimeError`) to Honeybadger. That seems ok to me, although we may want to create a real exception for this case (`ServerResponseError` or something).

**Comment by lmcglohon** [comment]
@drh-stanford I think the current behavior is fine.  So should we close this issue?

**Comment by drh-stanford** [comment]
Ok, closing
