### ISSUE TITLE
deploy, reset, and reindex in prod

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/discovery-dispatcher#90]
When we get an error condition the default behavior is to send the exception to Honeybadger and retry (up to 10 times). Is this what we want?

Each exception is per druid and we want to know that that druid fail due to bad data.

But if sw-indexer, for example, notices that the druid has bad data, it could log it in a reasonable way and return a _200_ success to discovery dispatcher. Since we _know_ that a job retry is not going to work.

Also see https://github.com/sul-dlss/base_indexer/issues/33 for some context

**Comment by blalbrit** [comment]
We want this to be reported via the auditing framework. We also want it to stop trying on bad data, but definition of "bad" is tricky as Preview takes a different set of criteria than Prod.

**Comment by lmcglohon** [comment]
Includes rebuilding of index through updated indexer code after #114 and redeployment of the code.

**Comment by drh-stanford** [comment]
This is underway, but still has 200k jobs to process

**Comment by drh-stanford** [comment]
The pipeline finished all 871k jobs -- it only failed on 168 of them, presumably valid failures (i.e., bad data).

![screen shot 2016-09-15 at 11 15 47 am](https://cloud.githubusercontent.com/assets/1861171/18561692/c6b10896-7b35-11e6-9ad7-bdc5f31826b1.png)
